package ${groupId}.${domain}.contract;

import ${groupId}.${domain}.${domainCamelCase}ControllerImpl;
import ${groupId}.${domain}.service.${domainCamelCase}Service;
import io.restassured.module.mockmvc.RestAssuredMockMvc;
import org.junit.Before;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Base class for the contract tests on the Producer side.
 * The tests are generated by Spring Cloud in the target folder: generated-test-sources/contracts
 */
public class BaseContractTest {

    @Before
    public void setup() {

        ${domainCamelCase}Service ${domain}ServiceMock = configure${domainCamelCase}ServiceMock();

        RestAssuredMockMvc.standaloneSetup(
                new ${domainCamelCase}ControllerImpl(${domainCamelCase}ServiceMock));
    }

    private ${domainCamelCase}Service configure${domainCamelCase}ServiceMock() {

        ${domainCamelCase}Service ${domain}Service = mock(${domainCamelCase}Service.class);

        return ${domain}Service;
    }
}
